package mocks_redlock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RedLock is an autogenerated mock type for the RedLock type
type RedLock struct {
	mock.Mock
}

// AcquireLock provides a mock function with given fields: ctx, key, attempts
func (_m *RedLock) AcquireLock(ctx context.Context, key string, attempts int) error {
	ret := _m.Called(ctx, key, attempts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, key, attempts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AcquireLockWithTTL provides a mock function with given fields: ctx, key, ttl, attempts
func (_m *RedLock) AcquireLockWithTTL(ctx context.Context, key string, ttl time.Duration, attempts int) error {
	ret := _m.Called(ctx, key, ttl, attempts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, int) error); ok {
		r0 = rf(ctx, key, ttl, attempts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReleaseLock provides a mock function with given fields: ctx, key
func (_m *RedLock) ReleaseLock(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRedLock creates a new instance of RedLock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedLock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedLock {
	mock := &RedLock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
